logging:
  file:
    path: logs
  level:
    com.mih.webauthn: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.h2: DEBUG
spring:
  jackson:
    default-property-inclusion: non_absent
    serialization:
     FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
webauthn:
  relying-party-id: localhost
  relying-party-name: Example Application
  relying-party-icon: http://localhost:8080/assets/logo.png
  relying-party-origins: http://localhost:8080
  endpoints:
    registrationStartPath: /api/registration/start
    registrationAddPath: /api/registration/add
    registrationFinishPath: /api/registration/finish
    assertionStartPath: /api/assertion/start
    assertionFinishPath: /api/assertion/finish
